name: ci

on:
    push:
        branches:
            - "**"
        tags:
            - "v*"
    pull_request:
        branches:
            - "master"
    workflow_dispatch:

permissions:
    packages: write
    contents: read

jobs:
    native:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: 20
            - run: npm ci
            - run: npm run lint
            - run: npm run typecheck
            - run: npm run test

    docker:
        environment: Docker Hub
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Docker meta
              id: meta
              uses: docker/metadata-action@v5
              with:
                  images: |
                      ghcr.io/${{ github.repository_owner }}/cross-seed
                      crossseed/cross-seed
                  tags: |
                      type=semver,pattern=version-{{version}}
                      type=semver,pattern={{version}}
                      type=semver,pattern={{major}}.{{minor}}
                      type=semver,pattern={{major}}
                      type=ref,event=branch
                      type=ref,event=pr
            - name: Set up QEMU dependency
              uses: docker/setup-qemu-action@v3
            - name: Set up Docker Buildx
              id: buildx
              uses: docker/setup-buildx-action@v3
            - name: Login to GHCR
              if: ${{ !github.event.pull_request.head.repo.fork }}
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.repository_owner }}
                  password: ${{ secrets.GITHUB_TOKEN }}
            - name: Login to DockerHub
              if: ${{ !github.event.pull_request.head.repo.fork }}
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: Get npm version
              id: get_version
              run: |
                VERSION=$(node -p "require('./package.json').version")
                echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
            - name: Get Git revision
              id: get_revision
              run: |
                REVISION=$(git rev-parse HEAD)
                echo "REVISION=$REVISION" >> $GITHUB_OUTPUT
            - name: Get creation time
              id: get_created
              run: |
                CREATED=$(date -u +'%Y-%m-%dT%H:%M:%SZ')
                echo "CREATED=$CREATED" >> $GITHUB_OUTPUT
            - name: Build and push
              uses: docker/build-push-action@v5
              with:
                  push: ${{ !github.event.pull_request.head.repo.fork }}
                  platforms: linux/amd64,linux/arm64
                  tags: ${{ steps.meta.outputs.tags }}
                  labels: ${{ steps.meta.outputs.labels }}
                  build-args: |
                      VERSION=${{ steps.get_version.outputs.VERSION }}
                      REVISION=${{ steps.get_revision.outputs.REVISION }}
                      CREATED=${{ steps.get_created.outputs.CREATED }}
